export const scrollArtLayers = [
  {
    id: "clouds",
    src: "/img/ai/clouds-ai.svg",
    alt: "Ilustração de nuvens geradas por IA",
    speed: 0.22,
    start: 0,
    end: 0.42,
    baseX: -12,
    baseY: 8,
    scale: 1.03,
  },
  {
    id: "fence",
    src: "/img/ai/fence-ai.svg",
    alt: "Ilustração de cercado gerada por IA",
    speed: 0.34,
    start: 0.24,
    end: 0.76,
    baseX: 9,
    baseY: 42,
    scale: 1,
  },
  {
    id: "juice",
    src: "/img/ai/juice-cup-spill.svg",
    alt: "Copo de suco derramando",
    speed: 0.46,
    start: 0.56,
    end: 1,
    baseX: -10,
    baseY: 68,
    scale: 1.07,
  },
];
