export const scrollArtLayers = [
  {
    id: "jar-morango",
    src: "/img/garrafinha.png",
    alt: "Jarra de suco de morango derramando",
    flavor: "morango",
    start: 0,
    end: 0.4,
    baseX: 10,
    baseY: 8,
    scale: 1,
    tilt: -12,
  },
  {
    id: "jar-maracuja",
    src: "/img/garrafinha02.png",
    alt: "Jarra de suco de maracujá derramando",
    flavor: "maracuja",
    start: 0.25,
    end: 0.75,
    baseX: 42,
    baseY: 8,
    scale: 1.02,
    tilt: -8,
  },
  {
    id: "jar-uva",
    src: "/img/garrafinha03.png",
    alt: "Jarra de suco de uva derramando",
    flavor: "uva",
    start: 0.55,
    end: 1,
    baseX: 74,
    baseY: 8,
    scale: 1,
    tilt: -10,
  },
];
