export const scrollArtLayers = [
  {
    id: "banner",
    src: "/img/banner.png",
    alt: "Banner KaSucos",
    speed: 0.24,
    start: 0,
    end: 0.42,
    baseX: -10,
    baseY: 4,
    scale: 1.02,
    swing: 3.6,
    float: 2.4,
    pointerDepth: 1.2,
  },
  {
    id: "about",
    src: "/img/about.png",
    alt: "Imagem de apresentação da KaSucos",
    speed: 0.3,
    start: 0.08,
    end: 0.58,
    baseX: 62,
    baseY: 10,
    scale: 0.95,
    swing: 4,
    float: 2.9,
    pointerDepth: 1.5,
  },
  {
    id: "garrafinha",
    src: "/img/garrafinha.png",
    alt: "Garrafinha KaSucos",
    speed: 0.35,
    start: 0.2,
    end: 0.82,
    baseX: 74,
    baseY: 42,
    scale: 0.9,
    swing: 5.2,
    float: 3.2,
    pointerDepth: 2,
  },
  {
    id: "garrafinha02",
    src: "/img/garrafinha02.png",
    alt: "Garrafinha KaSucos edição 2",
    speed: 0.42,
    start: 0.34,
    end: 1,
    baseX: 6,
    baseY: 58,
    scale: 0.88,
    swing: 5.6,
    float: 3.8,
    pointerDepth: 2.2,
  },
  {
    id: "garrafinha03",
    src: "/img/garrafinha03.png",
    alt: "Garrafinha KaSucos edição 3",
    speed: 0.5,
    start: 0.46,
    end: 1,
    baseX: 44,
    baseY: 70,
    scale: 0.94,
    swing: 6.3,
    float: 4.2,
    pointerDepth: 2.6,
  },
];
